package com.cap.day3;
class R1{
	public void m1() throws ArithematicException {
		int c=10/0;
	}	
}

public class Exception {
	

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		try {
			R1 r=new R1();
			r.m1();
		}
catch (ArithematicException e) {
	System.out.println("exception handled");
}
	}

}
